# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Runs e2e the tests"
  lane :e2e do
    Dir.chdir "../.." do
      sh("detox build --configuration ios.sim.release")
      sh("detox test --configuration ios.sim.release --cleanup")
    end
  end

  desc "Build a new version"
  lane :beta do
    increment_build_number(
      xcodeproj: "TicketsScanner.xcodeproj"
    )
    get_certificates   
    get_provisioning_profile
    build_app(
      workspace: "TicketsScanner.xcworkspace",
      scheme: "TicketsScanner",
      build_path: "./builds",
      output_directory: "./builds", 
      clean: true
    )
    clean_build_artifacts
  end
end
